project:
  type: website

website:
  title: "learn-relearn"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:FCSC
      - sidebar:PML
  sidebar:
    - id: FCSC
      title: "First Course in Stochastic Calculus"
      contents:
        - auto: FCSC
    - id: PML
      title: "Probabilistic Machine Learning"
      contents:
        - auto: PML

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
