project:
  type: website

website:
  title: "learn-relearn"
  page-navigation: true
  sidebar:
    style: "docked"
    contents:
      auto: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
